// Regenerate llms/llms-full.txt by concatenating the atomic topic files
// (llms/NN-*.md) in numeric order. The .md files are the single source of truth.
//
// Run with: npm run llms   (or: node scripts/build-llms.mjs)
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const llmsDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'llms');

// Atomic topic files are named `NN-title.md` so they sort deterministically.
const files = readdirSync(llmsDir)
  .filter((f) => /^\d{2}-.*\.md$/.test(f))
  .sort();

if (files.length === 0) {
  console.error('No atomic llms/NN-*.md files found — nothing to build.');
  process.exit(1);
}

const header = [
  '# @cosmosapp/pay_sdk — full documentation',
  '',
  'Object-oriented JavaScript/TypeScript SDK for the Cosmos Pay Payments API',
  '(Stellar SEP-7 payment intents, webhooks, products, customers, analytics).',
  '',
  'This single file concatenates every topic in llms/ for one-shot AI ingestion.',
  'Generated by scripts/build-llms.mjs — do not edit by hand; edit the NN-*.md files.',
  '',
].join('\n');

const sections = files.map((f) => readFileSync(join(llmsDir, f), 'utf8').trim());

const body = sections.join('\n\n---\n\n');
const out = `${header}\n${body}\n`;

writeFileSync(join(llmsDir, 'llms-full.txt'), out, 'utf8');
console.log(`Wrote llms/llms-full.txt from ${files.length} files (${out.length} bytes).`);
